# Tensor
-Tensor can be said as the representation of data in a multidimensional array

In [2]:
import torch

Everything in pytorch is based on Tensor operations.
A tensor can have different dimensions.
so it can be 1d, 2d, or even 3d and higher.
scalar, vector, matrix, tensor.
torch.empty(size): uninitiallized

In [10]:
x=torch.empty(1) #scalar
print(x)
print(x.dtype)
y=torch.empty(2,dtype=int) #we can initialize datatype
print(y)
z=torch.empty(3)# vector 1 d
print(" one d vector",z)
m=torch.empty(2,3)# matrix
print("tensor matrix",m)
t=torch.empty(2,2,3) #tensor ,3 dimensions
print("tensor ",t)


tensor([2.0944e+23])
torch.float32
tensor([              1, 140717106257928])
 one d vector tensor([9.6720e+00, 4.5911e-41, 3.6724e+12])
tensor matrix tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor  tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [12]:
#random initialization
x=torch.rand(3)
print(x)
y=torch.rand(3,2)
print(y)

tensor([0.1789, 0.1284, 0.4761])
tensor([[0.1273, 0.6425],
        [0.9266, 0.7386],
        [0.6058, 0.6165]])


In [13]:
print(torch.zeros(2,3))
print(torch.ones(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
print(x.size)
print(x.dtype)

<built-in method size of Tensor object at 0x0000015B47B74910>
torch.float32


In [17]:
#construct from data
x=torch.tensor([5.5,3])
print(x)
print(x.size())

tensor([5.5000, 3.0000])
torch.Size([2])


requires_grad argument 

This will tell pytorch that it will need to calculate the gradients for this tensor

later in your optimization steps


i.e. this is a variable in your model that you want to optimize

In [21]:
x=torch.tensor([5.5,3],requires_grad=True)



In [22]:
#operations
x=torch.rand(2,2)
y=torch.rand(2,2)

#element wise addition
z=x+y
print("addition result",z)


addition result tensor([[0.7091, 0.7411],
        [1.0108, 0.8213]])


torch.add(x,y)

in place addition, everythin with a trailing underscore is an inplace operation

 i.e. it will modify the variable

y.add_(x)

In [23]:
print(torch.add(x,y))


tensor([[0.7091, 0.7411],
        [1.0108, 0.8213]])


In [24]:
#subtraction
s=x-y
print(s)
print(torch.sub(x,y))

tensor([[ 0.6807, -0.1264],
        [ 0.4086,  0.1828]])
tensor([[ 0.6807, -0.1264],
        [ 0.4086,  0.1828]])


In [25]:
#similarly multiplication
m=x*y
print(m)
print(torch.mul(x,y))

tensor([[0.0099, 0.1333],
        [0.2137, 0.1603]])
tensor([[0.0099, 0.1333],
        [0.2137, 0.1603]])


# Slicing 
Slicing is a important concept to work with data.

In [33]:
x=torch.rand(5,3)
print(x)
print("\n")

print(x[:,0]) #all rows , column 0
print(x[1,:])#all columns , row 1
print(x[1,1])# element at 1,1
print(x[2,1]) # tensor at 2,1

tensor([[0.6314, 0.5932, 0.8567],
        [0.2685, 0.4976, 0.2538],
        [0.0144, 0.0581, 0.7994],
        [0.5817, 0.0655, 0.7220],
        [0.6301, 0.4691, 0.4298]])


tensor([0.6314, 0.2685, 0.0144, 0.5817, 0.6301])
tensor([0.2685, 0.4976, 0.2538])
tensor(0.4976)
tensor(0.0581)


In [35]:
#get the actual value if only 1 element in your tensor
print(x[1,1].item()) #prints the actual value at position 1,1

0.4975559711456299


In [38]:
# Reshape with torch.view
x=torch.rand(4,4)
y=x.view(16)
z=x.view(-1,8) # the size -1 is inferred from other dimensions
#if -1 it pytorch will automatically determine the necessary size
print(x.size(),y.size(),z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [40]:
#lets have a look on the tensors
print(x)
print("\n",y)
print("\n",z)

tensor([[0.1680, 0.6752, 0.9402, 0.6695],
        [0.6282, 0.8161, 0.8267, 0.8992],
        [0.3739, 0.2991, 0.5286, 0.6791],
        [0.8013, 0.5831, 0.1556, 0.7020]])

 tensor([0.1680, 0.6752, 0.9402, 0.6695, 0.6282, 0.8161, 0.8267, 0.8992, 0.3739,
        0.2991, 0.5286, 0.6791, 0.8013, 0.5831, 0.1556, 0.7020])

 tensor([[0.1680, 0.6752, 0.9402, 0.6695, 0.6282, 0.8161, 0.8267, 0.8992],
        [0.3739, 0.2991, 0.5286, 0.6791, 0.8013, 0.5831, 0.1556, 0.7020]])



### Converting a tensor torch into numpy array and vice vesa 

In [41]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [42]:
#torch to numpy using .numpy
b=a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Carful: If the Tensor is on the CPU (not the GPU),
both objects will share the same memory location, so changing one will also change the other

In [43]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##### Numpy to torch using .from_numpy(x)

In [44]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [45]:
# again be careful when modifying
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


by default all tensors are created on the CPU,
but you can also move them to the GPU (only if it's available )

In [46]:
if torch.cuda.is_available():
    device=torch.device("cuda") # a cuda device object
    y=torch.ones_like(x,device=device)# directly create a tensor on GPU
    x=x.to(device)# or just use string ''.to("cuda")
    x=x+y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    #move to cup again
    z.to("cpu") #  # ``.to`` can also change dtype together!