# Activation function
without activation fucntion we get only linear funtion. But sometimes linear function does not fit well when considering non linear or more complex examples. In this situation activation functions comes into consideration. There are several types of activation function.All are available in pytorch. they are -> 

- Step  :
    - outputs 1 if x>= threshold and 0 otherwise. not used in practice
- Sigmoid :
    - typically in the last layer of a binary classification problem
- TanH :
    - scaled sigmoid funcion with little bit shift. used in hidden layer
- ReLU  :
    - most popular choice. outputs 0 for negative values and for output for positive value.
    - if you dont know what to use then use ReLU
    - f(x)=max(0,x)

- Leaky ReLU :
     - slightly improved version of ReLU. x if x>=0 and a*x otherwise.
     - trying to solve the vanishing gradient problem
- softmax :
    -good in last layer in multiclass problems


In [14]:
import torch
import torch.nn as nn 
import torch.nn.functional as f 


- output = w*x + b
- output = activation_function(output)

In [15]:
x = torch.tensor([-1.0, 1.0, 2.0, 3.0])

In [16]:
# sofmax
output = torch.softmax(x, dim=0)
print(output)
sm = nn.Softmax(dim=0)
output = sm(x)
print(output)

tensor([0.0120, 0.0889, 0.2418, 0.6572])
tensor([0.0120, 0.0889, 0.2418, 0.6572])


In [17]:
# sigmoid 
output = torch.sigmoid(x)
print(output)
s = nn.Sigmoid()
output = s(x)
print(output)

tensor([0.2689, 0.7311, 0.8808, 0.9526])
tensor([0.2689, 0.7311, 0.8808, 0.9526])


In [18]:
#tanh
output = torch.tanh(x)
print(output)
t = nn.Tanh()
output = t(x)
print(output)

tensor([-0.7616,  0.7616,  0.9640,  0.9951])
tensor([-0.7616,  0.7616,  0.9640,  0.9951])


In [19]:
# relu
output = torch.relu(x)
print(output)
relu = nn.ReLU()
output = relu(x)
print(output)

tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])


In [20]:
# leaky relu
output = f.leaky_relu(x)
print(output)
lrelu = nn.LeakyReLU()
output = lrelu(x)
print(output)

tensor([-0.0100,  1.0000,  2.0000,  3.0000])
tensor([-0.0100,  1.0000,  2.0000,  3.0000])



nn.ReLU() creates an nn.Module which you can add e.g. to an nn.Sequential model.
torch.relu on the other side is just the functional API call to the relu function,
so that you can add it e.g. in your forward method yourself.

In [21]:
#option 1 (create nn modules)
class NeuralNet(nn.Module):
    def __init__(self,input_size,hidden_size):
        super(NeuralNet,self).__init__()
        self.linear1=nn.Linear(input_size,hidden_size)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(hidden_size,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        out=self.linear1(x)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out


In [22]:
#option 2 (use activation function directlyl in forward pass)
# option 2 (use activation functions directly in forward pass)
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(NeuralNet, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.linear2 = nn.Linear(hidden_size, 1)
    
    def forward(self, x):
        out = torch.relu(self.linear1(x))
        out = torch.sigmoid(self.linear2(out))
        return out